# Generated by Django 5.2.5 on 2025-09-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_remove_todo_completed_todo_is_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100, verbose_name="할일"),
        ),
    ]
