# Generated by Django 5.2.6 on 2025-09-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_due_date_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(verbose_name='마감기한'),
        ),
    ]
